### ISSUE TITLE
Cannot jump to reference

### ISSUE THREAD

**Issue by slgraf** [thomasthorsen/SublimeToks#13]
It seems like after indexing the repository, I can find references to an identifier. However I cannot jump to the reference (pressing enter on the dropdown list behaves as if I pressed the escape key).

Using Visual Studio 13 compiler.

**Comment by thomasthorsen** [comment]
Well that is depressing, I'm guessing you're on Windows then, which I don't test very much with, but it should of course work, so let's have a look.

I have a gut feeling that it might be due to a defect in how paths are put together. Are there any spaces or special characters in the path to the project? Can you try to open the console (View->Show Console) and see if any errors are printed when you select an item from the dropdown? If we're lucky there will be some error message from Python that can shed some light on what is going wrong.

**Comment by thomasthorsen** [comment]
Sounds a lot like issue #12 which i for some reason forgot all about ...

**Comment by slgraf** [comment]
Yeah, unfortunately I'm on windows *sigh*. I use Sublime for my job, and we're forced to use windows 7. 

No special characters, just underscores. Here is the error I'm getting: 

Traceback (most recent call last):
  File "C:\Users\graf\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 269, in on_highlighted
    view = sublime.active_window().find_open_file(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by slgraf** [comment]
Seems like 2 things are happening: 
1) the location returned on line 267 should be ran against os.path.normpath if the system is windows (to avoid escape sequences in the returned string)
2) the regex should be updated for windows

**Comment by slgraf** [comment]
Seems like that regex sequence did the trick. Both in is_same_location and on_highlighted, after that it works perfectly!  :D
